version: 2
updates:
  # C#
  - package-ecosystem: "nuget"
    directory: "/csharp"
    schedule:
      interval: "weekly"

  # Elixir
  - package-ecosystem: "hex"
    directory: "/elixir"
    schedule:
      interval: "weekly"

  # Go
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"

  # Java (Maven)
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"

  # Kotlin (Gradle)
  - package-ecosystem: "gradle"
    directory: "/kotlin"
    schedule:
      interval: "weekly"

  # Python
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"

  # Ruby
  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "weekly"

  # Rust
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
